apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    example: defaults
spec:
  dex:
    image: quay.io/ablock/dex
    version: openshift-connector
    openShiftOAuth: true
  ApplicationInstanceLabelKey: argocd.argoproj.io/instance
  resourceCustomizations: |
    PersistentVolumeClaim:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Pending" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
            if obj.status.phase == "Bound" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for certificate"
        return hs
  rbac:
    defaultPolicy: role:readonly
    policy: |
      g, argocdadmins, role:admin
      g, argocdusers, role:readonly
    scopes: "[groups]"